// Generated by CoffeeScript 1.6.3
(function() {
  var diameter, height, leftRightMargin, lineDrawer, marginBottom, width;

  document.body.innerHTML = "<svg class='chart'></svg>";

  marginBottom = 22;

  height = 300 + marginBottom;

  width = 600;

  leftRightMargin = 10;

  diameter = 2;

  lineDrawer = (function() {
    function lineDrawer(data) {
      var xAxis,
        _this = this;
      this.data = data;
      this.chart = d3.select('.chart').attr('width', width).attr('height', height);
      this.y = d3.scale.linear().domain([0, d3.max(_.flatten(this.data))]).range([height - marginBottom, 0]);
      this.x = d3.scale.linear().domain([0, this.data[0].length]).range([leftRightMargin, width - leftRightMargin]);
      this.line = d3.svg.line().interpolate("monotone").x(function(d, i) {
        return _this.x(i);
      }).y(this.y);
      _.each(this.data, function(_d, i, initial) {
        if (initial == null) {
          initial = true;
        }
        return _this.drawLine.apply(_this, arguments);
      });
      xAxis = d3.svg.axis().scale(this.x).orient("bottom");
      this.chart.append('g').attr('transform', function() {
        return "translate(0, " + (height - marginBottom) + ")";
      }).call(xAxis);
    }

    lineDrawer.prototype.drawLine = function(d, i, initial) {
      var empty;
      empty = d.map(function() {
        return 0;
      });
      if (initial) {
        this.chart.append("svg:path").attr("d", this.line(empty)).attr('class', "line" + i).transition().duration(500).attr("d", this.line(d));
      } else {
        this.chart.selectAll(".circle" + i).attr('cy', height - marginBottom);
        this.chart.select(".line" + i).attr("d", this.line(empty)).transition().duration(500).attr("d", this.line(d));
      }
      this.chart.selectAll(".circle" + i).data(empty).enter().append('circle').attr('class', "circle" + i).attr('cx', this.line.x()).attr('cy', this.line.y()).attr('r', diameter);
      return this.chart.selectAll(".circle" + i).data(d).transition().duration(500).attr('cx', this.line.x()).attr('cy', this.line.y());
    };

    lineDrawer.prototype.redrawLine = function(i) {
      return this.drawLine(this.data[i], i, false);
    };

    return lineDrawer;

  })();

  window.ld = new lineDrawer([[2, 5, 7, 3, 15, 4, 15, 2, 10, 10, 20, 6, 30, 10, 20], [2, 5, 2, 3, 2, 4, 2, 2, 10, 10, 20, 50, 30, 60, 20], [90, 10, 5, 100]]);

}).call(this);
