// Generated by CoffeeScript 1.6.3
(function() {
  var chart, data, height, leftRightMargin, line, marginBottom, width, x, xAxis, y;

  data = [2, 5, 7, 3, 15, 4, 15, 2, 10, 10, 20, 100, 30, 60, 20];

  document.body.innerHTML = "<svg class='chart'></svg>";

  marginBottom = 22;

  height = 100 + marginBottom;

  width = 300;

  leftRightMargin = 10;

  y = d3.scale.linear().domain([0, d3.max(data)]).range([height - marginBottom, 0]);

  x = d3.scale.linear().domain([0, data.length]).range([leftRightMargin, width - leftRightMargin]);

  chart = d3.select('.chart').attr('width', width).attr('height', height);

  line = d3.svg.line().interpolate("basis").x(function(d, i) {
    return x(i);
  }).y(y);

  chart.append("svg:path").attr("d", line(data));

  xAxis = d3.svg.axis().scale(x).orient("bottom");

  chart.append('g').attr('transform', function() {
    return "translate(0, " + (height - marginBottom) + ")";
  }).call(xAxis);

}).call(this);
